FROM node:18 as build
WORKDIR /usr/src/app
COPY package*.json ./
COPY src ./src
COPY tsconfig.json ./
RUN npm install
RUN npm install typescript -g
RUN tsc

FROM node:18-alpine
WORKDIR /usr/src/app
COPY .env ./
COPY package*.json ./
RUN npm install --only=production
COPY --from=build /usr/src/app/dist ./dist
CMD [ "node", "dist/main.js" ]